/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pagzone.view;

import com.pagzone.dao.OTPDao;
import com.pagzone.dao.UserDao;
import com.pagzone.props.CardLayoutChangeListener;
import com.pagzone.model.User;
import com.pagzone.service.EmailService;
import com.pagzone.util.Helper;
import com.pagzone.util.OTPHelper;
import com.pagzone.util.UserValidator;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author Chupaguio
 */
public class Signup extends javax.swing.JPanel {
    CardLayoutChangeListener listener;
            
    public Signup() {
        initComponents();
    }
    
    public Signup(CardLayoutChangeListener listener) {
        this.listener = listener;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChatIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblWelcomeBack = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        ptxtPassword = new javax.swing.JPasswordField();
        ptxtConfirmPassword = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        pnlSignUpLabels = new javax.swing.JPanel();
        lblNoAccount = new javax.swing.JLabel();
        lblSignUpLink = new javax.swing.JLabel();
        customTitleBar1 = new com.pagzone.component.CustomTitleBar();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(301, 411));

        lblChatIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChatIcon.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\chat_quote_icon.png"));

        lblTitle.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("<html><p><span style=\"color:#C72424;\">BulSU</span> Student Forum</p></html>");

        lblWelcomeBack.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        lblWelcomeBack.setForeground(new java.awt.Color(0, 0, 0));
        lblWelcomeBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeBack.setText("Create new account");

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        ptxtPassword.setBackground(new java.awt.Color(255, 255, 255));
        ptxtPassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ptxtPassword.setForeground(new java.awt.Color(0, 0, 0));
        ptxtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        ptxtConfirmPassword.setBackground(new java.awt.Color(255, 255, 255));
        ptxtConfirmPassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ptxtConfirmPassword.setForeground(new java.awt.Color(0, 0, 0));
        ptxtConfirmPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirm Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        btnSignup.setBackground(new java.awt.Color(199, 36, 36));
        btnSignup.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Sign Up");
        btnSignup.setBorder(null);
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        pnlSignUpLabels.setBackground(new java.awt.Color(255, 255, 255));
        pnlSignUpLabels.setForeground(new java.awt.Color(0, 0, 0));
        pnlSignUpLabels.setPreferredSize(new java.awt.Dimension(20, 20));

        lblNoAccount.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblNoAccount.setForeground(new java.awt.Color(0, 0, 0));
        lblNoAccount.setText("Already have an account?");
        pnlSignUpLabels.add(lblNoAccount);

        lblSignUpLink.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblSignUpLink.setForeground(new java.awt.Color(255, 102, 102));
        lblSignUpLink.setText("Sign in");
        lblSignUpLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignUpLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignUpLinkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSignUpLinkMousePressed(evt);
            }
        });
        pnlSignUpLabels.add(lblSignUpLink);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customTitleBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addComponent(pnlSignUpLabels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ptxtPassword)
                                    .addComponent(ptxtConfirmPassword)
                                    .addComponent(lblTitle)
                                    .addComponent(lblWelcomeBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSignup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 21, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblChatIcon)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customTitleBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblChatIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblWelcomeBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ptxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ptxtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSignUpLabels, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void lblSignUpLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpLinkMouseEntered
        Helper.setLabelUnderline((JLabel) evt.getSource(), true);
    }//GEN-LAST:event_lblSignUpLinkMouseEntered

    private void lblSignUpLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpLinkMouseExited
        Helper.setLabelUnderline((JLabel) evt.getSource(), false);
    }//GEN-LAST:event_lblSignUpLinkMouseExited

    private void lblSignUpLinkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpLinkMousePressed
        listener.changeCardLayout("login");
    }//GEN-LAST:event_lblSignUpLinkMousePressed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        if (validateFields()) {
            JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            EmailService emailService = new EmailService();
            String generatedOTP = OTPHelper.generateOTP();
            String email = txtEmail.getText().trim();
            String password = new String(ptxtPassword.getPassword()).trim();
            
            try {
                OTPDao.insertOTP(email, generatedOTP);
                emailService.sendOTPMail(email, generatedOTP);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(parentFrame, "An error has occured.", "SQL Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
            
            VerifyOTPDialog otpDialog = new VerifyOTPDialog(parentFrame, true, email, password);
            otpDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnSignupActionPerformed

    private boolean validateFields() {
        String email = txtEmail.getText().trim();
        String password = new String(ptxtPassword.getPassword()).trim();
        String confirmPassword = new String(ptxtConfirmPassword.getPassword()).trim();
            JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (UserValidator.verifySignup(email, password, confirmPassword)) {
            Helper.setTextFieldBorder(txtEmail, "E-mail", new Color(153,153,153));
            Helper.setTextFieldBorder(ptxtPassword, "Password", new Color(153,153,153));
            Helper.setTextFieldBorder(ptxtConfirmPassword, "Confirm Password", new Color(153,153,153));
            
            // verify if user already exists
            User user = UserDao.getUserByEmail(email);
            if (user != null) {
                JOptionPane.showMessageDialog(parentFrame, "An account with this email has already been created.", "Duplicate Email", JOptionPane.OK_OPTION);
                return false;
            }
            
            return true;
        } else {
            if (UserValidator.isValidEmail(email)) {
                Helper.setTextFieldBorder(txtEmail, "E-mail", new Color(153,153,153));
                if (!UserValidator.isValidBulsuEmail(email)) {
                    JOptionPane.showMessageDialog(parentFrame, "You must use your BulSU email account (@bulsu.edu.ph).", "Invalid Email", JOptionPane.OK_OPTION);
                }
            } else {
                Helper.setTextFieldBorder(txtEmail, "E-mail", new Color(199,36,36));
            }
            
            if (UserValidator.isValidPassword(password)) {
                Helper.setTextFieldBorder(ptxtPassword, "Password", new Color(153,153,153));
            } else {
                Helper.setTextFieldBorder(ptxtPassword, "Password", new Color(199,36,36));
            }
            
            if (UserValidator.isValidPassword(password) && password.equals(confirmPassword) ) {
                Helper.setTextFieldBorder(ptxtConfirmPassword, "Confirm Password", new Color(153,153,153));
            } else {
                Helper.setTextFieldBorder(ptxtConfirmPassword, "Confirm Password", new Color(199,36,36));
            }
            
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignup;
    private com.pagzone.component.CustomTitleBar customTitleBar1;
    private javax.swing.JLabel lblChatIcon;
    private javax.swing.JLabel lblNoAccount;
    private javax.swing.JLabel lblSignUpLink;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcomeBack;
    private javax.swing.JPanel pnlSignUpLabels;
    private javax.swing.JPasswordField ptxtConfirmPassword;
    private javax.swing.JPasswordField ptxtPassword;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
