/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pagzone.view.page;

import javax.swing.JCheckBox;

/**
 *
 * @author Arias
 */
public class Settings extends javax.swing.JPanel {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSettings = new javax.swing.JLabel();
        tpnlSettings = new javax.swing.JTabbedPane();
        pnlUserSettings = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblOldPassword = new javax.swing.JLabel();
        ptxtOldPassword = new javax.swing.JPasswordField();
        chkOldPassword = new javax.swing.JCheckBox();
        lblNewPassword = new javax.swing.JLabel();
        ptxtNewPassword = new javax.swing.JPasswordField();
        lblConfirmNewPassword = new javax.swing.JLabel();
        ptxtConfirmNewPassword = new javax.swing.JPasswordField();
        btnSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.BorderLayout());

        lblSettings.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        lblSettings.setForeground(new java.awt.Color(199, 36, 36));
        lblSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSettings.setText("Settings");
        add(lblSettings, java.awt.BorderLayout.PAGE_START);

        tpnlSettings.setBackground(new java.awt.Color(255, 255, 255));
        tpnlSettings.setForeground(new java.awt.Color(0, 0, 0));
        tpnlSettings.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        pnlUserSettings.setOpaque(false);

        lblUsername.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername.setText("Username");

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 0, 0));

        lblOldPassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblOldPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblOldPassword.setText("Old Password");

        ptxtOldPassword.setBackground(new java.awt.Color(255, 255, 255));
        ptxtOldPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ptxtOldPassword.setForeground(new java.awt.Color(0, 0, 0));

        chkOldPassword.setBackground(new java.awt.Color(255, 255, 255));
        chkOldPassword.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        chkOldPassword.setForeground(new java.awt.Color(102, 102, 102));
        chkOldPassword.setText("Show old password");
        chkOldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOldPasswordActionPerformed(evt);
            }
        });

        lblNewPassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblNewPassword.setText("New Password");

        ptxtNewPassword.setBackground(new java.awt.Color(255, 255, 255));
        ptxtNewPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ptxtNewPassword.setForeground(new java.awt.Color(0, 0, 0));

        lblConfirmNewPassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblConfirmNewPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblConfirmNewPassword.setText("Confirm New Password");

        ptxtConfirmNewPassword.setBackground(new java.awt.Color(255, 255, 255));
        ptxtConfirmNewPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ptxtConfirmNewPassword.setForeground(new java.awt.Color(0, 0, 0));

        btnSave.setBackground(new java.awt.Color(199, 36, 36));
        btnSave.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(null);

        javax.swing.GroupLayout pnlUserSettingsLayout = new javax.swing.GroupLayout(pnlUserSettings);
        pnlUserSettings.setLayout(pnlUserSettingsLayout);
        pnlUserSettingsLayout.setHorizontalGroup(
            pnlUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ptxtOldPassword)
                        .addComponent(txtUsername)
                        .addComponent(lblOldPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUserSettingsLayout.createSequentialGroup()
                        .addComponent(chkOldPassword)
                        .addGap(63, 63, 63)))
                .addGap(18, 18, 18)
                .addGroup(pnlUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ptxtNewPassword)
                        .addComponent(ptxtConfirmNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addComponent(lblNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblConfirmNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(186, 186, 186))
        );
        pnlUserSettingsLayout.setVerticalGroup(
            pnlUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserSettingsLayout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOldPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ptxtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkOldPassword))
                    .addGroup(pnlUserSettingsLayout.createSequentialGroup()
                        .addGroup(pnlUserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUserSettingsLayout.createSequentialGroup()
                                .addComponent(lblNewPassword)
                                .addGap(38, 38, 38)
                                .addComponent(lblConfirmNewPassword))
                            .addGroup(pnlUserSettingsLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(ptxtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(ptxtConfirmNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        tpnlSettings.addTab("User Settings", pnlUserSettings);

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        tpnlSettings.addTab("tab2", jPanel2);

        add(tpnlSettings, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void chkOldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOldPasswordActionPerformed
        JCheckBox curCheckBox = (JCheckBox) evt.getSource();
        if (curCheckBox.isSelected()) {
            ptxtOldPassword.setEchoChar((char) 0);
        } else {
            ptxtOldPassword.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_chkOldPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkOldPassword;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConfirmNewPassword;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblOldPassword;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlUserSettings;
    private javax.swing.JPasswordField ptxtConfirmNewPassword;
    private javax.swing.JPasswordField ptxtNewPassword;
    private javax.swing.JPasswordField ptxtOldPassword;
    private javax.swing.JTabbedPane tpnlSettings;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
