/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pagzone.view.page;

import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Arias
 */
public class Write extends javax.swing.JPanel {

    /**
     * Creates new form Write
     */
    public Write() {
        initComponents();
        setLayout(new MigLayout("wrap 1, insets 8 8 8 8",
                "[grow, fill][][]",
                "[][fill, grow][20:30:30]"));
        add(btnPost, "growy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPageTitle = new javax.swing.JLabel();
        spnlTextPane = new javax.swing.JScrollPane();
        txtpPost = new javax.swing.JTextPane();
        btnPost = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        lblPageTitle.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        lblPageTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblPageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPageTitle.setText("Write a post");
        add(lblPageTitle);
        lblPageTitle.setBounds(150, 10, 100, 28);

        txtpPost.setBackground(new java.awt.Color(255, 255, 255));
        txtpPost.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtpPost.setForeground(new java.awt.Color(0, 0, 0));
        spnlTextPane.setViewportView(txtpPost);

        add(spnlTextPane);
        spnlTextPane.setBounds(30, 40, 340, 230);

        btnPost.setBackground(new java.awt.Color(199, 36, 36));
        btnPost.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnPost.setForeground(new java.awt.Color(255, 255, 255));
        btnPost.setText("Post");
        btnPost.setBorder(null);
        add(btnPost);
        btnPost.setBounds(100, 290, 29, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPost;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JScrollPane spnlTextPane;
    private javax.swing.JTextPane txtpPost;
    // End of variables declaration//GEN-END:variables
}
