/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pagzone.view.page;

import com.pagzone.component.Loader;
import com.pagzone.dao.PostDao;
import com.pagzone.model.Post;
import com.pagzone.service.SessionManager;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Arias
 */
public class Write extends javax.swing.JPanel {

    /**
     * Creates new form Write
     */
    public Write() {
        initComponents();
        pnlContent.setLayout(new MigLayout("wrap 1",
                "[grow, fill]",
                "[][][][][fill, grow][][20:30:30]"));
        pnlContent.add(btnPost, "growy");
        updateContentTextCountLabel();
        
        txtaContent.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateContentTextCountLabel();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateContentTextCountLabel();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {}
        });
        
        updateTimestampLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLayered = new javax.swing.JLayeredPane();
        pnlContent = new javax.swing.JPanel();
        lblPageTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtTitle = new com.pagzone.component.LimitedTextField();
        lblContent = new javax.swing.JLabel();
        spnlTextArea = new javax.swing.JScrollPane();
        txtaContent = new com.pagzone.component.LimitedTextArea();
        pnlTextDetails = new javax.swing.JPanel();
        lblTimestamp = new javax.swing.JLabel();
        lblContentTextCount = new javax.swing.JLabel();
        btnPost = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.BorderLayout());

        pnlLayered.setLayout(new java.awt.BorderLayout());

        pnlContent.setOpaque(false);
        pnlContent.setLayout(null);

        lblPageTitle.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        lblPageTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblPageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPageTitle.setText("Write a post");
        pnlContent.add(lblPageTitle);
        lblPageTitle.setBounds(60, 40, 250, 28);

        lblTitle.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setLabelFor(txtTitle);
        lblTitle.setText("Title");
        lblTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnlContent.add(lblTitle);
        lblTitle.setBounds(60, 70, 23, 19);

        txtTitle.setBackground(new java.awt.Color(255, 255, 255));
        txtTitle.setForeground(new java.awt.Color(0, 0, 0));
        txtTitle.setCaretColor(new java.awt.Color(0, 0, 0));
        txtTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTitle.setMaxLength(50);
        pnlContent.add(txtTitle);
        txtTitle.setBounds(60, 90, 260, 30);

        lblContent.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblContent.setForeground(new java.awt.Color(0, 0, 0));
        lblContent.setLabelFor(txtaContent);
        lblContent.setText("Content");
        lblContent.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnlContent.add(lblContent);
        lblContent.setBounds(60, 130, 80, 19);

        spnlTextArea.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtaContent.setBackground(new java.awt.Color(255, 255, 255));
        txtaContent.setColumns(20);
        txtaContent.setForeground(new java.awt.Color(0, 0, 0));
        txtaContent.setLineWrap(true);
        txtaContent.setRows(5);
        txtaContent.setWrapStyleWord(true);
        txtaContent.setCaretColor(new java.awt.Color(0, 0, 0));
        txtaContent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtaContent.setMaxLength(500);
        spnlTextArea.setViewportView(txtaContent);

        pnlContent.add(spnlTextArea);
        spnlTextArea.setBounds(60, 150, 260, 110);

        pnlTextDetails.setOpaque(false);
        pnlTextDetails.setLayout(new java.awt.GridLayout(1, 2));

        lblTimestamp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTimestamp.setForeground(new java.awt.Color(102, 102, 102));
        lblTimestamp.setText("test");
        pnlTextDetails.add(lblTimestamp);

        lblContentTextCount.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblContentTextCount.setForeground(new java.awt.Color(102, 102, 102));
        lblContentTextCount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pnlTextDetails.add(lblContentTextCount);

        pnlContent.add(pnlTextDetails);
        pnlTextDetails.setBounds(30, 270, 260, 20);

        btnPost.setBackground(new java.awt.Color(199, 36, 36));
        btnPost.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnPost.setForeground(new java.awt.Color(255, 255, 255));
        btnPost.setText("Post");
        btnPost.setBorder(null);
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });
        pnlContent.add(btnPost);
        btnPost.setBounds(100, 290, 160, 22);

        pnlLayered.add(pnlContent, java.awt.BorderLayout.CENTER);

        add(pnlLayered, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        Loader loader = new Loader();
        pnlLayered.setLayer(loader, JLayeredPane.POPUP_LAYER);
        pnlLayered.add(loader, BorderLayout.CENTER);
        pnlLayered.validate();
        pnlLayered.repaint();
        
        setEnableInputs(false);
        createPost();
        setEnableInputs(true);
        
        pnlLayered.remove(loader);
    }//GEN-LAST:event_btnPostActionPerformed

    private void updateTimestampLabel() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("MMM dd, yyyy HH:mm:ss");
        String formattedDate = dateFormat.format(new Date());
        lblTimestamp.setText(formattedDate);
        
        startTimer();
    }

    private void startTimer() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateTimestampLabel();
            }
        });
        timer.start();
    }
    
    private void updateContentTextCountLabel() {
        lblContentTextCount.setText(getContentTextCount() + "/500");
        
        if (getContentTextCount() >= 500) {
            lblContentTextCount.setForeground(new Color(199,36,36));
        } else {
            lblContentTextCount.setForeground(new Color(102,102,102));
        }
    }
    
    private int getContentTextCount() {
        return txtaContent.getText().length();
    }
    
    private void createPost() {
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        SessionManager sessionManager = SessionManager.getInstance();
        String title = txtTitle.getText().trim();
        String content = txtaContent.getText().trim();
        
        if (title.length() > 0 && content.length() > 0) {
            try {
                Post post = new Post();
                post.setTitle(title);
                post.setUser(sessionManager.getCurrentUser());
                post.setBody(content);

                PostDao.createPost(post);
                clearInputs();
                JOptionPane.showMessageDialog(parentFrame, "Your post has been successfully published.",
                    "Post Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(parentFrame, "You must log in to be able to post.",
                        "User is not logged in", JOptionPane.ERROR_MESSAGE);
            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(parentFrame, ex.getMessage(),
                        "An error has occured", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(parentFrame, "Both fields are required!",
                    "Missing Fields", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void clearInputs() {
        txtTitle.setText("");
        txtaContent.setText("");
    }
    
    private void setEnableInputs(boolean value) {
        txtTitle.setEnabled(value);
        txtaContent.setEnabled(value);
        btnPost.setEnabled(value);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPost;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblContentTextCount;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblTimestamp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JLayeredPane pnlLayered;
    private javax.swing.JPanel pnlTextDetails;
    private javax.swing.JScrollPane spnlTextArea;
    private com.pagzone.component.LimitedTextField txtTitle;
    private com.pagzone.component.LimitedTextArea txtaContent;
    // End of variables declaration//GEN-END:variables
}
