/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pagzone.component;

import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Arias
 */
public class CreatePost extends javax.swing.JPanel {

    /**
     * Creates new form CreatePost
     */
    public CreatePost() {
        initComponents();
        setLayout(new MigLayout("wrap 2, gap 5", "[28:28:28][grow, fill]", "[]"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfilePicture = new javax.swing.JLabel();
        txtPost = new javax.swing.JTextField();

        setBackground(new java.awt.Color(199, 36, 36));
        setLayout(null);

        lblProfilePicture.setBackground(new java.awt.Color(229, 203, 203));
        lblProfilePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_icon_red_28.png"))); // NOI18N
        lblProfilePicture.setOpaque(true);
        add(lblProfilePicture);
        lblProfilePicture.setBounds(10, 10, 40, 42);

        txtPost.setBackground(new java.awt.Color(255, 255, 255));
        txtPost.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtPost.setBorder(null);
        add(txtPost);
        txtPost.setBounds(60, 10, 390, 42);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JTextField txtPost;
    // End of variables declaration//GEN-END:variables
}
