/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pagzone.component;

/**
 *
 * @author Arias
 */
public class Loader extends javax.swing.JPanel {

    /**
     * Creates new form Loader
     */
    public Loader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoaderIcon = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        lblLoaderIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoaderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loader_animation_red_72.gif"))); // NOI18N
        add(lblLoaderIcon, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLoaderIcon;
    // End of variables declaration//GEN-END:variables
}
