/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pagzone.view.page.post;

import com.pagzone.model.Post;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Arias
 */
public class PostDialog extends javax.swing.JDialog {
    private Point initialClick;
    
    public PostDialog(java.awt.Frame parent, boolean modal, Post post) {
        super(parent, modal);
        initComponents();
        applyMouseListener();
        
        setTitle(post.getTitle());
        postPage1.setPost(post);
        postPage1.showPostDetails();
    }
    
    private void applyMouseListener() {
        PostDialog parentFrame = this;
        pnlHeader.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                initialClick = e.getPoint();
                getComponentAt(initialClick);
                setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
            }
            
            @Override
            public void mouseReleased(MouseEvent e) {
                setCursor(Cursor.getDefaultCursor());
            }
        });
        
        pnlHeader.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                if (parentFrame != null) {
                    // Get current location of the JFrame
                    int thisX = parentFrame.getLocation().x;
                    int thisY = parentFrame.getLocation().y;

                    // Calculate how much the mouse moved since the initial click
                    int xMoved = e.getX() - initialClick.x;
                    int yMoved = e.getY() - initialClick.y;

                    // Move the JFrame to this position
                    int X = thisX + xMoved;
                    int Y = thisY + yMoved;
                    parentFrame.setLocation(X, Y);
                } else {
                    try {
                        System.out.println(parentFrame.getName());    
                    } catch (Exception err) {
                        err.getCause();
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPostDialog = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblContainer = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblTItle = new javax.swing.JLabel();
        postPage1 = new com.pagzone.view.page.post.PostPage();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Post");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPostDialog.setBackground(new java.awt.Color(255, 255, 255));
        pnlPostDialog.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(199, 36, 36));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblContainer.setOpaque(false);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_icon.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        lblContainer.add(lblClose);

        pnlHeader.add(lblContainer, java.awt.BorderLayout.LINE_START);

        lblTItle.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblTItle.setForeground(new java.awt.Color(255, 255, 255));
        lblTItle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTItle.setText("BulSU Student Forum");
        pnlHeader.add(lblTItle, java.awt.BorderLayout.CENTER);

        pnlPostDialog.add(pnlHeader, java.awt.BorderLayout.NORTH);
        pnlPostDialog.add(postPage1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlPostDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClose;
    private javax.swing.JPanel lblContainer;
    private javax.swing.JLabel lblTItle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPostDialog;
    private com.pagzone.view.page.post.PostPage postPage1;
    // End of variables declaration//GEN-END:variables
}
