/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pagzone.view.page.post;

import com.pagzone.model.Post;
import com.pagzone.util.Helper;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Arias
 */
public final class PostItem extends javax.swing.JPanel {
    private Post post;
    /**
     * Creates new form PostItem
     */
    public PostItem() {
        initComponents();
        setLayout(new MigLayout("wrap 2", "[grow, fill][]", "[][]"));
        add(lblTitle, "span 2");
        add(lblUsername);
        add(lblTimestamp);
    }
    
    public PostItem(Post post) {
        initComponents();
        setLayout(new MigLayout("wrap 2", "[grow, fill][]", "[][]"));
        add(lblTitle, "span 2");
        add(lblUsername);
        add(lblTimestamp);
        
        this.post = post;
        
        showPostDetails();
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    
    public void showPostDetails() {
        lblTitle.setText(post.getTitle());
        lblUsername.setText(post.getUser().getUsername());
        lblTimestamp.setText(Helper.formatTimestamp(post.getTimestamp()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblTimestamp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(199, 36, 36));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Title");
        add(lblTitle);
        lblTitle.setBounds(7, 7, 38, 28);

        lblUsername.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        add(lblUsername);
        lblUsername.setBounds(10, 40, 70, 19);

        lblTimestamp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTimestamp.setForeground(new java.awt.Color(255, 255, 255));
        lblTimestamp.setText("Timestamp");
        add(lblTimestamp);
        lblTimestamp.setBounds(80, 40, 70, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTimestamp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
