/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pagzone.view.page.post;

import com.pagzone.model.Post;
import com.pagzone.util.Helper;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Arias
 */
public final class PostPage extends javax.swing.JPanel {
    private Post post;
    
    public PostPage() {
        initComponents();
        initLayout();
    }
    
    public PostPage(Post post) {
        initComponents();
        initLayout();
        
        this.post = post;
        showPostDetails();
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    
    public void showPostDetails() {
        lblTitle.setText(post.getTitle());
        lblUsername.setText(post.getUser().getUsername());
        lblTimestamp.setText(Helper.formatTimestamp(post.getTimestamp()));
        lblBody.setText(post.getBody());
    }
    
    private void initLayout() {
        setLayout(new MigLayout("wrap 2", "[][]", "[][][fill, grow]"));
        add(lblTitle, "span 2");
        add(lblUsername);
        add(lblTimestamp);
        add(lblBody, "span 2, gaptop 5");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblTimestamp = new javax.swing.JLabel();
        lblBody = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(199, 36, 36));
        lblTitle.setText("Title");
        lblTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblTitle);
        lblTitle.setBounds(6, 6, 230, 37);

        lblUsername.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(51, 51, 51));
        lblUsername.setText("Username");
        add(lblUsername);
        lblUsername.setBounds(6, 40, 61, 19);

        lblTimestamp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTimestamp.setForeground(new java.awt.Color(51, 51, 51));
        lblTimestamp.setText("Timestamp");
        add(lblTimestamp);
        lblTimestamp.setBounds(110, 40, 66, 19);

        lblBody.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblBody.setForeground(new java.awt.Color(0, 0, 0));
        lblBody.setText("Body");
        lblBody.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblBody);
        lblBody.setBounds(10, 60, 120, 123);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBody;
    private javax.swing.JLabel lblTimestamp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
